### ISSUE TITLE
Desature Issues

### ISSUE THREAD

**Issue by Kumase** [Maczuga/WeakAuras2-MoP#6] opened 2020-11-10 15:35 UTC
Enabling the Desature option under the Display tab should desature the icon. Nothing happens.

Using a condition to desature the icon does work but it also has a few issues, mainly with DoTs for what I could tell.

I'm personally tracking 2 debuffs, using a condition to desature them, that part works fine. My trigger is set to go off when the debuff are found on the target and a condition to remove the desaturation when this is true.

Clicking anyone or anything, makes both DoTs show up on color, even without casting the dots until you either /reload or open up /wa

Before Clicking
![image](https://user-images.githubusercontent.com/43862731/98693782-7bb85a80-234f-11eb-89e1-38a7d7a96d71.png)

After Clicking
![image](https://user-images.githubusercontent.com/43862731/98693734-6e02d500-234f-11eb-8d77-bc0e11e81a85.png)

Dots Found
![image](https://user-images.githubusercontent.com/43862731/98694019-be7a3280-234f-11eb-8662-f831792eabfd.png)

Another issue I found, is that when you try to track the duration of a buff and its cooldown, using a condition doesn't properly apply it. For example, in my case I'm tracking Starfalls duration and the cooldown:

As seen in previous images, it shows up in color, after using the skill:
![image](https://user-images.githubusercontent.com/43862731/98694459-3a747a80-2350-11eb-9865-2efec89d81af.png)

Once the duration wears off, trying to use a condition of "Cooldown = True - Desature ✓" keeps the icon with color. A workaround for this is setting an additional condition that tracks while the buff is active and the duration is less than 0.1 to desaturate it.

**Comment by Maczuga** [comment] 2020-11-10 15:54
Please export your weak aura so I can confirm this on my character.

**Comment by Kumase** [comment] 2020-11-10 16:00
!WA:2!1r1ZUnsXt41YSAblbIyqjSbKqebb0EiczjcxGdEsSzdYXoASZMS7bS7zMYZ0Bg3DVD3J)Zcli8P9SFeMZCkpcrio3YcX5Fkpc5j4x19yVzbb(G7UQP7Q(QV6RRsnRoQAu1Ox(P50qoRlptgcF0DwsY0jCzhHMYzQkYzDgoub6sxsyHO)t4uMo4GgT71WFziNNgXNW6oHkGbxT2SrumKijHUiSVVstK6kbdPmQkPIhUORmxlPXXGu9o7kxT9pKzkOnzem4Avwamgy6UzdhsNEz)dQ3Tx)U9Q73B5iIombuDt4t6WYv4s90jKzkF3fcEiqs1jEzyocW0gdAp9mb4tYKKAZvcin9OivLfwBgMl12ZpMZzdPsqIiVdlD2TP)ejGP3V7jnA1Y3D6k5rqacQEymLpSU)XnpT1Im2QkOIydBrpg6vyFmpc(T7CdsyGKrsFewUiJ05MlaquhXsO2NGCuYcfKo0rSM7Ijqr0i60qsoceFi2YIp4LBk(enmv3393qUejI(I(A6iOVqcHuBOlV4vhzNptiExNLkHGnLd4PC53xQuPYxx492ukEpNhSVZXGsdpJgHuyD08MIKrNcroN)6YcrWJxPjUY99NMP00HZqSl5Ae39qNET70UHzljwb2ZK7oyOddLXFlwvfmDEJPi8vkShkQ(A4DDk(BopFLZLoFt4YOZKeX8ZwTz5RIQR)050EToQDJv0WRjFn3Ta4JrslifgiU))cZwSX3sWr3g4U0Nd3FflSgnIp()QXendvn0WK)AzCkFstj8SmGfo7K34l3R2xvWo2pCfk8)U0v9OK5wx2cyzqMwJ6LXGmLml36UfWI1jBCPD)AgAr86R6Ow33wdnpRrIl79sOHxWqMUS7cDdjPqX2wu09gU47HmjitcsaACIUUxkNe9Ofi86hMsuQbZTBTk3b(oh7gOOS4uW)q)tp6q)rzPA6MMhpWZEMDnNx28KTrdK0208Kk5sNy2wBE2ro5y06HZm0uXa50vq28ddeFanMXLWQzqnSVfBiLCPAG3Z58ro(7RfV)65nwb3Hufb7LrjEwD8GCnpCCX7T383)F7qJmFyTmA0Lbp9lcdf7FO0)OlhkXN0D14tns5BkAPnTUS4lO7b(nA02FIv2xpi0oIiUIKYSbfs8Vvk7tsfjKY54rIOo8(GD9XruHx0082LNpMiPwGfyhBar(JjPzqPD4ID(MVvgMqyXaEbJEWCHKJIw9mZNBnnJTV(3R2E22YUMNzdMrEnmvqL2HgSEOaZORwRiuMSTlULzY810sYccJoYD49nVvZLrzf3SVDIiwfweRmB5X4m4kGOSCHtFDV5wllnyEH3icL108JMFYSL5fMF(EMFbxQ8p9uvv7qyC1X)55))

Looks like its the same, the only difference is that I selected "Show If Unit Does Not Exist" to always show it.

**Comment by Kumase** [comment] 2020-11-10 16:00
!WA:2!1v1YUTTrx4yOFJKFHUOrP1OjOan1aXlkqnSLDstlAlGOSuJdCKmivItbsH0qYdjNeYzyNzOU4DvRYIwKw9iO1DLEem6daHqrxxKhb)e0ZmKYXPx0cPZCMZ1V5C(0ATRLuZVM)l3Co1JZC4zcp4dVIThpMlEyf8Jys3GajOwBbH5fXfhZPmLBZwD61YEPhNh7ZhXCgrtHbNT6yl)qiYshWbtvcAyiiKD2suk(YBSWhCZccAgtKYnStiHuVbltikViq6eXh1LnxI)0iEezI81YmxyiWuhlGa6yBNJBD0rZZyuvRXuPsoyHhpXLYGhX9HfA)EanedKAErw6njfepOH9JA)4JSu4bBsMGu)8mj0)s1rKwrRXepLtkehFO)aBtwDFaqIvr2msciRwxaj13z7DT053vreHGAQSWbz1lkvhmQ0Xl63SHtV(o9Ay3Bb6yxSqikUO2xFMUemUr9L3Y6(FE9DfiU1LfpzGlwh2qs0SmwjGvDHpv(8mMNIoeQtytsVoXi3R4EDJ)Rx5C8Dbems8tq0MYzDp)faK2aZINYMOO8bZimAIwIDpBjw7Q25ByX4m4mGibhLayHQORU0hloTv91OLqc47OVCQ2gnwMVRvcHYqFZ3nV(vZ3lF)87MVRBaLrLr)D14JGKO0beIMJWJneIrw(fV8dsRPGXQ(YicoY80YHS0BAuA(kGlWQTVSuiF3zxC3M3jn9DVK7nnJRRT2AvEDHwioWmOMVE6nmAizkUU39oH6RISAGhpVil0XGVr5pSSyc)BlRLZm3)8mPIgmjF95cUc7IEOsRoD70kFdb2pABMBm8nRmZklFMAERXPcqkX54Y29TtXBHbRuU8c3nJUDFCVJoStRcTJ4c)teK0PNukuuKdPsQBmmOeuU0MkcaF8)ast7ROjqFS08O6rL)nypTuWwBQ)BQjh6PWNwIux8Q9r)xPWFcU3q9I(JLHX8rTfW3NbmVjh))2z763Tab1xSq)1QOnvFW06nA6eHl2Z1koYmC((glxHuZ0hAEbUFgU58nR0ezPVmYyIJhjgQykHEruVxWWNKkMBocdV86MeyHikiIcw6Ae6ZlYr(gZWISq3zLx59MXTsnREawuEgqgW0BAftp9uIW)2n8IOiXqcsnC7t4C)vMjrWCD3iajSuhAfZj(pzMMxYtZinyQwuV)oW2OylxjLfgd2hy)4dpWojlwrRAPnyRCrLCfkJXBduyUWSMzwxVMqtwG7C3lFNQw4sQQA(NzOusJjtoexUtVZHAQJaIh8m9z5ZmuG97OxCH(oivrBsCC67TIFxVdCavsWo2pY6uop54k7S9ElXLmCQOBQjDvNR4Edl4IU2V9NBs9N(ioNfqfq9mQ)I49dFsMh9HNS3P2K40isf7r61WVtmU459D()UEA7dRkOmDGGOZlM7AlqYyDZ5600UvRolc0kqcmIIS(CnDf1ucFYw24FP49I7LxTY0HebvxXUAkFW3Eijodwt4fryHG8wBL)QbttfCCStnj)(BL)JTrVY)PxdJtPf8H9Wj68xvB)n5PB(LFv(pB8j)x00ABxFB9m00vi0GzxIcQMS(bWWAd)9N(xp

Looks like its the same, but I selected "Show If Unit Does Not Exists" to keep the icon always visible.

**Comment by Maczuga** [comment] 2020-11-10 19:30
More investigations: this is only related to Icon, as Textures works fine.

Working Texture example:
```!WA:2!1rvZUnsrqyB8kXIvoKywLvB0kXsKic2SGq5qqIt4XzmXGJNSTN8dsGS7zMYE6nJ7UP7ESJZjWApSN9JGpZP8eGI4byKfpaO9apa5jyRESJz5pFWtn1uvxF1x)vvX6vgujQs0R(4zSqbVTivfcpUGASxVEAWC4xfo7l)PcfENRP8WyH6ybJBcQ52Y3LmpuisIeJ4ThXKq3BU7v3O(qSIgAycUEFI2qvMYb9yCMoUSd(WuEIrX63hu6w7OwA(NZ0XIr1seCqhRs1ql6aO7uAQIYrl9wtosi49ykqH1WJNmUlbgciAoeOjMysEuLNLINV7LmTr31Xmwce7jS3eTessAePl)ADAqEEhRGESljTp2TzthBwbiq7dM5dOMWyq3gHJhphvvtgrhRxLz70EyMx3Pw12(DA7xL4plccqN(y9uhwLCu9tAonLVSZkFDet)IuosidH9O8XYnO52(l((rIi4xkClsSGIttofPfK58U9caKvrChAiuKlJNs5Sbwl((z3V(navdTnkG33e)UzB6WrMBEe2S2i6yBDLgWR0i9eBOwSLTRZakJxp7Pycz7M9SSpn7ZWNV3)0d2pAQXEwqSCde(HkWaDuct(PxCgsfeOV9cERx9qzfdCPPJoMIx)NVq4uu(OCN5)1tOqG3rV0iB3PR(22FKuU(BLEnrIq9nflwS0Rx4fs6Ll6CQEIVN89ZDstnclteEglYe7ufF92ffIDjeL78NNVqW(DlHZn5F)fPAdR34S7nlVvaF0PtlVwUzBQWwYgZS8adZHrj830LDa3ixVUID1tEEkncjg6t89)Bn(DvA(QeYLdEN43Srl3fEhjurNPOYjNT0ybSgY0SGeO7sM4Tg1KB0OvlxshhpFFVJin(6d9LF4)IyLDmSbqhPcczwTtP)dYxU0Gydn6VazB2vWJwswRU7(G)VsenghZyHXbXaRFS5LRfSGi76KiOr77yLRBsgKMyyLjHjuTEZStl7OXIynYVLsvGT1TYE5dQ1S6rh7750SATVT6bh0WVXPUbdykLqfptLlXYPXLjofPjEKnvItt3whCDpfo2JJb4fsPPRelz3tD5Yfy)6d)rC)vHcz)GC922La6VVkkSjPC4lCSR86kFWDBUSYHdyAkwKOyNReIbfNzeHdxmrE)F7p2MfTTGheAxe1VmHMiJPLiJScUxU2TliX6wezXCq7Aex3w7LYIU(5N9j7D(a)lOT7RyC7bcXZrzmgVNmFrjsxR0CZSJTSC3BTdbxgfEX(zR9Sctgsvml622JeK7w)u8dLYmb21pqezinjfkI(ECHmZ0yQEXoTSrfvHXuEFCp6ozJ6orQewsDC2Np5UMpEYQX7k69oagwz4VF(B(d```

**Comment by Maczuga** [comment] 2020-11-10 21:20
So... After some hours of testing I am no longer sure whether it is a port bug or retail WA just works that way. Most wago imports I have found operated on separate auras for found/not found.

I came up with what I think expected result via this WA. Please check if that is what you wanted.

```!WA:2!1vv3UnXXx8g5IkALQkyGebTveG2O)CdIMQgbPTQ1BWPWFzST21uO3uVZU7X7oK1ZSmZS2X5o8vCB9JGvFc8JquvVE0QQk17QYJqEc6zgVoa9JCr85CMZN)oFSRTF9H1JRh)QBnNgXz(8cre8rVJxepJl()1W)et6myGeu)8hSGWIs5IUCktfUxZ29A6vgX5zX8Xm)X0Ci44vSnJtGaxJhdMQe0Keqi)XTevK)QOqcTjdHGzKcbHHuYRn9XCoBavaLdjQOuq6NYh3HDS0(tJifDe4bJam2peizQ0tKfHw(Ucya9qp)UnB1YZ6mNPYCil7rXshbMnDyztcCvtYbpt82(ml9lgGwUO)En8713VxdVEUfmQkurejGAEmeIk0dTt8WgEpE)N0AwbRQgC2s78Ql7PeKOdCjfkE(fXIQFcWabnAzUhu(wSZnLsJSXKjs9hgMNrMac9hlEyZwDrxR3iuQiQc5uJFmPrGOGztt9n011xsFzh9fYV6Evq8MDf8ebiLB()8nf7TZVKXq4qsKQVT8niCAPabl)vS63V0O0zphOVIZSZ4o)n)d9v1xBAmcskkNv)ZMz02wJbNyijHsUi8X8y0YRVU(w6pzrmv(8cMT9SnHnj)IelDVLWKr1ANIdmGGrY(ECma9BNtpaG8gyCJuEMiLoJWOdTXChpefeQ9pgisWxjawIk990B4Y4mOCvM130mfsahWILtnQA6s6DDhsOS913hnqVR(l1FL(R17goGYOY0)UyS9kr8gDiKohNi8Ge0ZYDF1g51vWHiiMsqG(zlh)xl)QwH2)nGlWSTVSIqV7SZE7MFAE(fEdZ3ZUiT2ARv7KLsHSb2ni95YVKvIz4Xu7rpLgRsDBGSNUmk0dHyRWxwUC17hQYLJTV)8cPIoyI(CZfCCYb6HcDB3PDt9gcSEm6m3Q4RxMNvL(m18MhMBMEWPX3QCF7qmIkPHzqqPLBmxe)ubjF6tRikpZD2LKopPxRh1Uzv9)gxlWA9g)d0lVVIoe6Jzre1mvu7FbHZRi8mQg)6W5tpcUDfOCwd66)xHiEcEvGgL(7Ljz8X7lGxuaSOjDF37ENT)ILGL5HJXj8VlRQLLo1iYuwLHfkfo0oce4k7CJ4w2PYRSWqVcWMLSYulsBFBvQ5AysTrVxkn6agc81Sg4hrYGLKTOO4lA9VlIVGiDGEJzyUfA5wS8N(sS0RDCfZR7SNujzvhBL6aEj(e3m6rhreXB2fxTMuw9eFzYfMc0Ku1lDZ4K4DCnBLR7nSitrD8IYis566XoUMWAiMlSRj21TZhgzozN4KF5vh(nZGpGkjykehC6Yg0(c82IXGq)98A2S9CeN7H6RO5bUhX5d7w7U35Z13iyUIhnA5jIZ)l)5nPX5xy1hf2ubWlIjXcZ1fClDh99C0FJJlUzRCwmWeb8ybrrQ5n2UXioSc73UGgVWR992P9K7)OM7nwqzMyaPZEJvXsCjeZ0o5wN7m3CxHAPV2wE4hJIoyhTtTPJicQP0CnxY9grYkG1erPewc(bST0)uW0Cbhxeut0F70vqsQhjlpLuRUC7haJQp63E2Fn
```

**Comment by Maczuga** [comment] 2020-11-10 21:31
Note to myself: check UnitAura tommorow? But doubt that's gonna do anything since Texture is working.

**Comment by Kumase** [comment] 2020-11-11 06:26
> So... After some hours of testing I am no longer sure whether it is a port bug or retail WA just works that way. Most wago imports I have found operated on separate auras for found/not found.
> 
> I came up with what I think expected result via this WA. Please check if that is what you wanted.
> 
> `!WA:2!1vv3UnXXx8g5IkALQkyGebTveG2O)CdIMQgbPTQ1BWPWFzST21uO3uVZU7X7oK1ZSmZS2X5o8vCB9JGvFc8JquvVE0QQk17QYJqEc6zgVoa9JCr85CMZN)oFSRTF9H1JRh)QBnNgXz(8cre8rVJxepJl()1W)et6myGeu)8hSGWIs5IUCktfUxZ29A6vgX5zX8Xm)X0Ci44vSnJtGaxJhdMQe0Keqi)XTevK)QOqcTjdHGzKcbHHuYRn9XCoBavaLdjQOuq6NYh3HDS0(tJifDe4bJam2peizQ0tKfHw(Ucya9qp)UnB1YZ6mNPYCil7rXshbMnDyztcCvtYbpt82(ml9lgGwUO)En8713VxdVEUfmQkurejGAEmeIk0dTt8WgEpE)N0AwbRQgC2s78Ql7PeKOdCjfkE(fXIQFcWabnAzUhu(wSZnLsJSXKjs9hgMNrMac9hlEyZwDrxR3iuQiQc5uJFmPrGOGztt9n011xsFzh9fYV6Evq8MDf8ebiLB()8nf7TZVKXq4qsKQVT8niCAPabl)vS63V0O0zphOVIZSZ4o)n)d9v1xBAmcskkNv)ZMz02wJbNyijHsUi8X8y0YRVU(w6pzrmv(8cMT9SnHnj)IelDVLWKr1ANIdmGGrY(ECma9BNtpaG8gyCJuEMiLoJWOdTXChpefeQ9pgisWxjawIk990B4Y4mOCvM130mfsahWILtnQA6s6DDhsOS913hnqVR(l1FL(R17goGYOY0)UyS9kr8gDiKohNi8Ge0ZYDF1g51vWHiiMsqG(zlh)xl)QwH2)nGlWSTVSIqV7SZE7MFAE(fEdZ3ZUiT2ARv7KLsHSb2ni95YVKvIz4Xu7rpLgRsDBGSNUmk0dHyRWxwUC17hQYLJTV)8cPIoyI(CZfCCYb6HcDB3PDt9gcSEm6m3Q4RxMNvL(m18MhMBMEWPX3QCF7qmIkPHzqqPLBmxe)ubjF6tRikpZD2LKopPxRh1Uzv9)gxlWA9g)d0lVVIoe6Jzre1mvu7FbHZRi8mQg)6W5tpcUDfOCwd66)xHiEcEvGgL(7Ljz8X7lGxuaSOjDF37ENT)ILGL5HJXj8VlRQLLo1iYuwLHfkfo0oce4k7CJ4w2PYRSWqVcWMLSYulsBFBvQ5AysTrVxkn6agc81Sg4hrYGLKTOO4lA9VlIVGiDGEJzyUfA5wS8N(sS0RDCfZR7SNujzvhBL6aEj(e3m6rhreXB2fxTMuw9eFzYfMc0Ku1lDZ4K4DCnBLR7nSitrD8IYis566XoUMWAiMlSRj21TZhgzozN4KF5vh(nZGpGkjykehC6Yg0(c82IXGq)98A2S9CeN7H6RO5bUhX5d7w7U35Z13iyUIhnA5jIZ)l)5nPX5xy1hf2ubWlIjXcZ1fClDh99C0FJJlUzRCwmWeb8ybrrQ5n2UXioSc73UGgVWR992P9K7)OM7nwqzMyaPZEJvXsCjeZ0o5wN7m3CxHAPV2wE4hJIoyhTtTPJicQP0CnxY9grYkG1erPewc(bST0)uW0Cbhxeut0F70vqsQhjlpLuRUC7haJQp63E2Fn`

Exactly what I was looking for! Thank you very much.

In any case, the Desaturate option for Icons doesn't work at all (the one under the Display tab). It works fine for textures as you previously mentioned.

**Comment by Maczuga** [comment] 2020-11-12 21:23
Fixed in https://github.com/Maczuga/WeakAuras2-MoP/commit/ae98782f296cba178ad01cadd18f242e787a077a

**Closed by Maczuga** 2020-11-12 21:23 UTC
Labels: bug
